import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar">
        <Link href="/" className="navbar-item">홈</Link>
        <span>|</span>
        <Link href="/list" className="navbar-item">리스트</Link>
        <span>|</span>
        <Link href="/write" className="navbar-item">작성</Link>
      </div>
      <div className="body-content bg-neutral-800 text-white">
          {children}
      </div>
      </body>
    </html>
  )
}
